POST https://icy-flower-2825.fly.dev/api/persons
Content-Type: application/json

{ 
    "name": "John Doe", 
    "number": "01-45-7832122"
}
###
POST http://localhost:3001/api/persons
Content-Type: application/json

{ 
    "name": "John Deere", 
    "number": "01-45-7832122"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{ 
    "name": null,
    "number": ""
}